package com.abhishek.model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jul 01 13:33:54 IST 2018
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    Boolean isRowLocked();
}

